services:
  diun:
    image: crazymax/diun:4.28
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
    labels:
      - "diun.enable=true"
    restart: "unless-stopped"

  updater:
    build: . 
    env_file:
      - .env
    volumes:
      - .:/app
      - "/var/run/docker.sock:/var/run/docker.sock"
#    ports:
#      - "2990:3000"
    restart: "unless-stopped"

  cron:
    image: jsonfry/curl-cron
    environment:
      - "CRON_SCHEDULE=0 * * * *"
      - "OPTIONS=http://updater:3000/cron"
    restart: "unless-stopped"
